version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cut_video_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cut_video_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
